#!/bin/zsh
# Regenerate Flip.xcodeproj after Xcode Cloud clones the repo.
#
# Why this has to exist: `App/Flip.xcodeproj/` is gitignored (.gitignore:52) and
# generated by xcodegen from `App/project.yml`, which is the arrangement that
# keeps a capability added in Xcode's GUI from being silently dropped by the
# next `generate`. The cost is that a fresh clone has no project at all, so
# Xcode Cloud has nothing to open and the build dies seconds in. This is the
# step that makes a clone buildable. `Flip/Flip.entitlements` is generated the
# same way, from project.yml's `entitlements.properties`, so it lands here too.
#
# Contract, from Apple's "Writing custom build scripts" and "Making dependencies
# available to Xcode Cloud":
#   * this directory must sit beside the .xcodeproj -- App/ci_scripts, not the
#     repo root -- and Xcode Cloud runs the script FROM here;
#   * Homebrew is present in the build environment, `sudo` is not;
#   * the file needs the executable bit AND a shebang, or Xcode Cloud runs it as
#     `zsh <file>` and the build can fail on that alone;
#   * a non-zero exit fails the build, which is what we want when this cannot
#     produce a project.
set -e

# Resolved from the script's own path rather than CI_PRIMARY_REPOSITORY_PATH:
# that variable was never verified against Apple's reference, while the working
# directory is documented. Same idiom the repo's `music` script uses.
cd "${0:A:h}/.."

brew install xcodegen
xcodegen generate

# `set -e` catches a generator that exits non-zero. It does NOT catch one that
# reports success and writes nothing, and "no project" is precisely the state
# this script exists to prevent -- so check the artifact, not the exit code.
if [[ ! -d Flip.xcodeproj ]]; then
  print -u2 "ci_post_clone: xcodegen reported success but produced no Flip.xcodeproj in $PWD"
  exit 1
fi
print "ci_post_clone: generated $PWD/Flip.xcodeproj"
